### ISSUE TITLE
Updating to Blender 2.80

### ISSUE THREAD

**Issue by Modanung** [reattiva/Urho3D-Blender#90]
> Blender 2.80 is now in the beta stage of development and is being prepared for a final release. Add-on authors can now work on updating their code to run on 2.80. The Python API should be considered mostly stable, but there may be some minor chages related to bug fixing and user feedback. Breaking changes may still happen, but will be kept to a minimum. 

[Blender 2.80: Python API Changes](https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API)

Blend files saved with Blender 2.80 are not backwards compatible with older versions of Blender. So once a file is saved in 2.80, you cannot open them is 2.79b to use the exporter.

**Comment by 1vanK** [comment]
Internal renderer removed from blender 2.8...

**Comment by 1vanK** [comment]
We can add custom Cycles node (by grouping https://docs.blender.org/manual/en/dev/editors/node_editor/nodes/groups.html  ) with all required inputs and export data from it

**Comment by Modanung** [comment]
I updated [TiNA](https://gitlab.com/Modanung/TiNA) so it can be used with Blender 2.80 Beta. You can see the changes that were required in this case [here](https://gitlab.com/Modanung/TiNA/commit/be81448d3fa88700b00ae2436be9f6c279235628).

**Comment by reattiva** [comment]
Still pondering and waiting, probably I'll go down with the ship.

**Comment by Modanung** [comment]
Most changes should amount to a careful _replace all_. I intend to have a look and try to walrus through, but I'd say there's no reason to rush it... or give up hope.
@reattiva Also don't underestimate the value of your contributions. This add-on is the default conduit by which 3D content is fed into Urho, and it's doing a _great job_! I honestly cannot thank you enough.

**Comment by Modanung** [comment]
I created a [fork](https://github.com/Modanung/Urho3D-Blender/tree/b2.80) here:

**Comment by Modanung** [comment]
@reattiva [These](https://github.com/reattiva/Urho3D-Blender/compare/master...Modanung:b2.80) changes were quite trivial. Could you maybe identify more work that would need to be done?

**Comment by Modanung** [comment]
I must admit I do no quite understand the implications of [this](https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Addons#Naming) API change.

**Comment by reattiva** [comment]
Modanung, thanks for your encouragement and your work.
Lets wait for the beta to end, the lazy me says.
As 1vanK said, exporting the textures must be translated to eevee by intercepting some nodes.
No idea about the names' rules, I'll check if I see any warning.

**Comment by ghost** [comment]
> As 1vanK said, exporting the textures must be translated to eevee by intercepting some nodes.

I'm thinking maybe that part could be left out (commented?) until the end of beta, lazy _me_ says.
If that would make the exporter functional for geometry data there will be earlier rejoicing.

**Comment by ghost** [comment]
...and a 2.80 version of the add-on will not function in 2.79 anyway. So I'm thinking it would be best to make a final _release_ for 2.79 and to accept the not-as-essential material/texture exporting to be absent from the 2.80 version at first.

@reattiva I also noticed my branch was missing some modification you made, which have now been merged into the [b2.80 branch](https://github.com/Modanung/Urho3D-Blender/tree/b2.80).

**Comment by reattiva** [comment]
~~https://github.com/reattiva/Urho3D-Blender/tree/2.80~~
https://github.com/reattiva/Urho3D-Blender/tree/2_80 (thanks dertom95)
It ain't much but it's honest work.

**Comment by ghost** [comment]
The add-on seems to be loaded correctly, but I don't see the export panel anywhere. The _Render_ properties seem to - since Blender 2.80* - have been split up into a _Render_ and a _Output_ properties. Could it be registered to something non-existent?

**Comment by reattiva** [comment]
I can find it in the Render sub-panel of the Properties panel (Blender 2019-03-25).
Check the console for errors, if there are none it should be somewhere.

**Comment by ghost** [comment]
Right... :zzz::male_detective:

```
fake_module: addon missing 'bl_info' gives bad performance!: '/home/frode/.config/blender/2.80/scripts/addons/decompose.py'
fake_module: addon missing 'bl_info' gives bad performance!: '/home/frode/.config/blender/2.80/scripts/addons/export_scene.py'
fake_module: addon missing 'bl_info' gives bad performance!: '/home/frode/.config/blender/2.80/scripts/addons/export_urho.py'
fake_module: addon missing 'bl_info' gives bad performance!: '/home/frode/.config/blender/2.80/scripts/addons/utils.py'
Modules Installed () from '/home/frode/Downloads/Urho3D-Blender-2.80.zip' into '/home/frode/.config/blender/2.80/scripts/addons'
```

It also does not show up in the list of add-ons, btw.

**Comment by dertom95** [comment]
@Modanung @reattiva 
That also took me some time to figure out and resulted in a big WTF :D
The problem is that: 'Urho3D-Blender-2.8' (as the folder will be named by github zip-export) is not a valid python-module name. The solution for my plugin was to use 2.8 as master (which results in Urho3d-Blender-master as name) I guess just renaming the branch to "twopointeight" would also work....I'm also working on a 2.8-port for some time on and off with some additional features including materials(own urho-related-nodetrees) , collection-support and some kind of live-preview (external to blender) which will be ready for an experimental 'release' when I find the time during the easter-days.

**Comment by ghost** [comment]
@dertom95 Renaming the folder in the zip indeed fixed the problem, and the add-on seems to work! :D

**Comment by ghost** [comment]
As @QBkGames mentioned on the forums, the very latest build of Blender seems to break things again:
```
AttributeError: 'Context' object has no attribute 'depsgraph'
```

**Comment by jforjustin** [comment]
A `decompose.py` for bleeding-edge Blender 2.8.
Seems to export models and XML but I have done little testing.
diff https://pastebin.com/45LGJ9b4  full https://pastebin.com/Y5EnKtpb
Issues I caused:
 always applies modifiers
 meshes are assumed not double-sided
 temporary shapekey meshes (?) are not removed
